/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runner_lib_Server_ChangeTitle */

#ifndef _Included_runner_lib_Server_ChangeTitle
#define _Included_runner_lib_Server_ChangeTitle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runner_lib_Server_ChangeTitle
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_runner_lib_Server_ChangeTitle_setTitle
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
